baseURL = 'https://example.org/'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'
title = 'My New Hugo Site'
theme = 'reimu'

[languages]
[languages.zh-CN]
languageName = '简体中文'
weight = 1
hasCJKLanguage = true
